### ISSUE TITLE
Critical Error: Invalid memory read/write

### ISSUE THREAD

**Issue by SaSukiTB** [AndreVallestero/multi-pixel-get-color#1]
Hi thank you for this awsome script, can you please help why i get this Error (invalid memory read and write) here 
`return NumGet(mpgcScan0 + 0, x * 4 + y * mpgcStride, "UInt")`

Here is an example how you get the error :

![AutoHotkeyU32_dr6uWUbyTG](https://user-images.githubusercontent.com/20482574/181862294-6c1b1e6b-a245-42c0-9712-2bd24d1161d4.jpg)

Just press both button at the same time (Multiple time).

**Comment by AndreVallestero** [comment]
This is likely because you cleanup the memory buffer as you're trying to read from it on the second key press. `init_mpgc()` should only be called at when your program starts, and `end_mpgc()` should only run when the program ends.

I would rewrite it like this:

```
; program start
init_mpgc()

~1 Up::
~2 Up::
update_mpgc()
mpgc(11, 11)
return

End::
end_mpgc()
return
```

In reality though, you're only getting one pixel at a time, you should probably use the built-in AHK implementation for getting the color at a pixel. This library is for getting multiple pixel colors before updating.
